import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
function App(){
 const [messages,setMessages]=useState([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[token,setToken]=useState(''),[notice,setNotice]=useState('');
 async function api(path,body){const r=await fetch('/api'+path,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(125000)});const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:'Request validation failed');return data;}
 async function send(e){e.preventDefault();if(!input.trim()||busy)return;const message=input;setInput('');setBusy(true);setError('');setMessages(m=>[...m,{role:'You',answer:message}]);try{const data=await api('/chat',{message});setMessages(m=>[...m,{role:'Assistant',...data}]);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function upload(e){const f=e.target.files[0];if(!f)return;if(f.size>100000){setNotice('Choose a UTF-8 text file under 100 KB.');return;}setBusy(true);try{const result=await api('/documents',{source:f.name,text:await f.text()});setNotice(`Indexed ${result.chunks} chunks from ${result.source}`);}catch(e){setNotice(e.message);}finally{setBusy(false);e.target.value='';}}
 return <div className="layout"><aside><div className="logo">E / AI</div><h2>Enterprise<br/>AI workspace</h2><p>Ask questions. Inspect evidence. Build trust.</p><label>Access token<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="JWT for authenticated environments" autoComplete="off"/></label><small>Kept in memory for this session.</small><label className="upload">Add knowledge<input type="file" accept=".txt,.md" onChange={upload} disabled={busy}/></label><small>UTF-8 text / Markdown · Admin access</small><p role="status">{notice}</p></aside><main><header><span>KNOWLEDGE & OPERATIONS</span><h1>Your enterprise, in context.</h1><p>Answers backed by your documents, with a visible evidence trail.</p></header><section aria-label="Conversation" aria-live="polite">{messages.length===0?<div className="empty"><h2>Start with a question</h2><p>Try “What is the refund window?” or “What is the service status?”</p><p className="muted">Local default: demo mode. OpenAI and PostgreSQL are enabled through server configuration.</p></div>:messages.map((m,i)=><article key={i} className={m.role==='You'?'user':''}><div className="meta">{m.role} {m.route&&<span>{m.blocked?'Blocked':m.route}</span>}</div><p className="answer">{m.answer}</p>{m.citations?.length>0&&<details><summary>Retrieved evidence · {m.citations.length}</summary>{m.citations.map(c=><blockquote key={c.chunk_id}><strong>{c.source}</strong><p>{c.snippet}</p></blockquote>)}</details>}</article>)}{busy&&<p role="status">Working…</p>}</section>{error&&<p role="alert" className="error">{error}</p>}<form onSubmit={send}><label htmlFor="message" className="sr">Message</label><textarea id="message" value={input} maxLength={8000} onChange={e=>setInput(e.target.value)} placeholder="Ask about your company knowledge…"/><button disabled={busy||!input.trim()}>Send ↗</button></form><footer>Verify important answers against the retrieved sources. Each request is independent.</footer></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
